import { useMemo, useState } from 'react';
import {
  ArrowLeft, Pencil, Phone, Mail, Landmark, CalendarDays, Car, Wallet, Receipt,
  TrendingUp, CheckCircle2, CalendarClock,
} from 'lucide-react';
import { supabase, Vehicle, VehicleOwner, FinanceTransaction } from '../../lib/supabase';
import { STATUS_META, fmt, WEEKLY_OWNER_PAYOUT_DEFAULT, OWNER_PAYOUT_DAYS_PER_WEEK, MONTHLY_MANAGEMENT_FEE_DEFAULT } from '../../lib/finance';
import { formatDateLabelSafe } from '../../lib/fleet';
import DataTable from '../../components/DataTable';
import SetVehicleStartDateDrawer from '../../components/finance/SetVehicleStartDateDrawer';

const PAYMENT_DAY_LABEL: Record<string, string> = {
  monday: 'Monday', tuesday: 'Tuesday', wednesday: 'Wednesday', thursday: 'Thursday',
  friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday',
};

function isOnboardingOrSetup(t: FinanceTransaction): boolean {
  if (t.type === 'onboarding_fee') return true;
  if (t.type === 'supplier_payment' && /^(Device cost|Branding cost|Uniforms)/.test(t.description ?? '')) return true;
  return false;
}

function isMonthlyFee(t: FinanceTransaction): boolean {
  return t.type === 'revenue' && !!t.description?.startsWith('Monthly management fee');
}

// Everything about one vehicle owner in one place: their bank details,
// every car they have with Kivu and its payout schedule, and the three
// kinds of money that flow because of that relationship - the one-time
// onboarding fee and its setup costs, the recurring monthly management
// fee, and the weekly payout itself. All read back from finance_transactions
// (already generated by onboard_vehicle_owner/confirm_onboarding_fee/
// sync_vehicle_obligations on the server) - this page just totals and
// lists what's already there, and lets Finance/the MD act on anything
// still pending.
export default function VehicleOwnerProfilePage({
  owner,
  vehicles,
  transactions,
  canEdit,
  onBack,
  onEditOwner,
  reload,
}: {
  owner: VehicleOwner;
  vehicles: Vehicle[];
  transactions: FinanceTransaction[];
  canEdit: boolean;
  onBack: () => void;
  onEditOwner: () => void;
  reload: () => void;
}) {
  const [schedulingVehicle, setSchedulingVehicle] = useState<Vehicle | null>(null);
  const [actingId, setActingId] = useState<string | null>(null);
  const [error, setError] = useState('');

  const ownedVehicles = useMemo(() => vehicles.filter((v) => v.owner_id === owner.id), [vehicles, owner.id]);
  const ownedVehicleIds = useMemo(() => new Set(ownedVehicles.map((v) => v.id)), [ownedVehicles]);
  const ownerTx = useMemo(
    () => transactions.filter((t) => t.linked_vehicle_id && ownedVehicleIds.has(t.linked_vehicle_id)),
    [transactions, ownedVehicleIds],
  );

  const onboardingRows = useMemo(
    () => ownerTx.filter(isOnboardingOrSetup).sort((a, b) => b.transaction_date.localeCompare(a.transaction_date)),
    [ownerTx],
  );
  const monthlyFeeRows = useMemo(
    () => ownerTx.filter(isMonthlyFee).sort((a, b) => b.transaction_date.localeCompare(a.transaction_date)),
    [ownerTx],
  );
  const weeklyPaymentRows = useMemo(
    () => ownerTx.filter((t) => t.type === 'vehicle_owner_payment').sort((a, b) => b.transaction_date.localeCompare(a.transaction_date)),
    [ownerTx],
  );

  const totalPaid = weeklyPaymentRows.filter((t) => t.status === 'posted').reduce((s, t) => s + t.amount, 0);
  const totalPending = ownerTx.filter((t) => t.status === 'pending').reduce((s, t) => s + t.amount, 0);
  const pendingCount = ownerTx.filter((t) => t.status === 'pending').length;

  const confirmPaid = async (txId: string) => {
    setActingId(txId);
    setError('');
    const { error: err } = await supabase.rpc('mark_vehicle_owner_payment_paid', { p_transaction_id: txId });
    setActingId(null);
    if (err) { setError(err.message); return; }
    reload();
  };

  const actOn = async (t: FinanceTransaction) => {
    setActingId(t.id);
    setError('');
    const rpc = t.type === 'onboarding_fee' ? 'confirm_onboarding_fee' : 'approve_pending_transaction';
    const { error: err } = await supabase.rpc(rpc, { p_transaction_id: t.id });
    setActingId(null);
    if (err) { setError(err.message); return; }
    reload();
  };

  const actionColumn = (labelFor: (t: FinanceTransaction) => string, onClick: (t: FinanceTransaction) => void) => ({
    header: '',
    className: 'text-right',
    render: (t: FinanceTransaction) => (
      canEdit && t.status === 'pending' ? (
        <button onClick={() => onClick(t)} disabled={actingId === t.id} className="btn-primary text-[11px] px-2.5 py-1.5 disabled:opacity-50">
          {actingId === t.id ? 'Working…' : labelFor(t)}
        </button>
      ) : null
    ),
  });

  const statusColumn = {
    header: 'Status',
    render: (t: FinanceTransaction) => (
      <span className="text-[9px] font-medium px-1.5 py-0.5 rounded-full" style={{ backgroundColor: `${STATUS_META[t.status].color}20`, color: STATUS_META[t.status].color }}>
        {STATUS_META[t.status].label}
      </span>
    ),
  };

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <button onClick={onBack} className="btn-ghost flex items-center gap-1.5">
          <ArrowLeft size={14} /> Back to Vehicle Owners
        </button>
        {canEdit && (
          <button onClick={onEditOwner} className="btn-primary flex items-center gap-1.5">
            <Pencil size={13} /> Edit
          </button>
        )}
      </div>

      {error && <div className="text-[11px] text-red-600 bg-red-50 dark:bg-red-500/10 rounded-lg px-3 py-2">{error}</div>}

      <div className="card p-5">
        <div className="flex items-start justify-between gap-3 flex-wrap mb-3">
          <div>
            <h2 className="text-lg font-semibold">{owner.full_name}</h2>
            <p className="text-[11px] text-gray-400 mt-0.5">{ownedVehicles.length} vehicle{ownedVehicles.length === 1 ? '' : 's'}</p>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="card p-2.5 bg-gray-50 dark:bg-white/5">
            <p className="text-[9px] font-semibold uppercase tracking-wide text-gray-400 mb-1 flex items-center gap-1"><Phone size={10} /> Phone</p>
            <p className="text-[12px] font-medium">{owner.phone}</p>
          </div>
          <div className="card p-2.5 bg-gray-50 dark:bg-white/5">
            <p className="text-[9px] font-semibold uppercase tracking-wide text-gray-400 mb-1 flex items-center gap-1"><Mail size={10} /> Email</p>
            <p className="text-[12px] font-medium truncate">{owner.email || <span className="text-gray-400 font-normal">Not provided</span>}</p>
          </div>
          <div className="card p-2.5 bg-gray-50 dark:bg-white/5">
            <p className="text-[9px] font-semibold uppercase tracking-wide text-gray-400 mb-1 flex items-center gap-1"><Landmark size={10} /> Bank Account</p>
            <p className="text-[12px] font-medium truncate">{owner.bank_name ? `${owner.bank_name}${owner.account_number ? ` · ${owner.account_number}` : ''}` : <span className="text-gray-400 font-normal">Not set</span>}</p>
          </div>
          <div className="card p-2.5 bg-gray-50 dark:bg-white/5">
            <p className="text-[9px] font-semibold uppercase tracking-wide text-gray-400 mb-1 flex items-center gap-1"><CalendarDays size={10} /> Payment Day</p>
            <p className="text-[12px] font-medium">{owner.payment_day ? PAYMENT_DAY_LABEL[owner.payment_day] : <span className="text-gray-400 font-normal">Not set</span>}</p>
          </div>
        </div>

        {owner.notes && (
          <div className="mt-3">
            <p className="text-[10px] font-semibold uppercase tracking-wide text-gray-400 mb-1.5">Notes</p>
            <p className="text-[12px] leading-relaxed whitespace-pre-wrap">{owner.notes}</p>
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <div className="card p-4">
          <div className="flex items-center gap-1.5 mb-2">
            <div className="w-6 h-6 rounded-lg bg-emerald-50 dark:bg-emerald-500/10 flex items-center justify-center shrink-0"><Wallet size={12} className="text-emerald-600 dark:text-emerald-300" /></div>
            <p className="stat-label">Total Paid Out</p>
          </div>
          <p className="text-2xl font-bold leading-none">{totalPaid.toLocaleString()}</p>
          <p className="text-[10px] text-gray-400 mt-1.5">RWF posted across all weekly payouts</p>
        </div>
        <div className="card p-4">
          <div className="flex items-center gap-1.5 mb-2">
            <div className="w-6 h-6 rounded-lg bg-amber-50 dark:bg-amber-500/10 flex items-center justify-center shrink-0"><CheckCircle2 size={12} className="text-amber-600 dark:text-amber-300" /></div>
            <p className="stat-label">Needs Action</p>
          </div>
          <p className="text-2xl font-bold leading-none">{totalPending.toLocaleString()}</p>
          <p className="text-[10px] text-gray-400 mt-1.5">RWF across {pendingCount} pending item{pendingCount === 1 ? '' : 's'}</p>
        </div>
        <div className="card p-4">
          <div className="flex items-center gap-1.5 mb-2">
            <div className="w-6 h-6 rounded-lg bg-brand/10 flex items-center justify-center shrink-0"><Car size={12} className="text-brand-600 dark:text-brand-300" /></div>
            <p className="stat-label">Managed Cars</p>
          </div>
          <p className="text-2xl font-bold leading-none">{ownedVehicles.length}</p>
          <p className="text-[10px] text-gray-400 mt-1.5">{ownedVehicles.map((v) => v.plate_number).join(', ') || '—'}</p>
        </div>
      </div>

      {/* Vehicles & payout schedule */}
      <div className="card p-4">
        <p className="text-[11px] font-semibold uppercase tracking-wide text-gray-400 mb-2.5 flex items-center gap-1.5"><CalendarClock size={13} /> Vehicles &amp; Payout Schedule</p>
        {ownedVehicles.length === 0 ? (
          <p className="text-[11px] text-gray-400">No vehicles linked to this owner yet.</p>
        ) : (
          <div className="space-y-1.5">
            {ownedVehicles.map((v) => (
              <div key={v.id} className="flex items-center justify-between gap-3 py-1.5 border-b border-gray-50 dark:border-white/5 last:border-0">
                <div className="min-w-0">
                  <p className="text-[12px] font-medium flex items-center gap-1.5"><Car size={11} className="text-gray-400 shrink-0" /> {v.plate_number}</p>
                  <p className="text-[10px] text-gray-400 mt-0.5">
                    {v.operation_start_date
                      ? <>Since {formatDateLabelSafe(v.operation_start_date)} · {fmt(Math.round((v.weekly_owner_payout_amount ?? WEEKLY_OWNER_PAYOUT_DEFAULT) / OWNER_PAYOUT_DAYS_PER_WEEK))}/day ({fmt(v.weekly_owner_payout_amount ?? WEEKLY_OWNER_PAYOUT_DEFAULT)}/week) · {fmt(v.monthly_management_fee_amount ?? MONTHLY_MANAGEMENT_FEE_DEFAULT)}/month</>
                      : <span className="text-red-500 dark:text-red-400">No start date set — payments won't generate until it is</span>}
                  </p>
                </div>
                {canEdit && (
                  <button onClick={() => setSchedulingVehicle(v)} className="btn-ghost shrink-0 whitespace-nowrap text-[11px] px-2.5 py-1.5">
                    {v.operation_start_date ? 'Edit Schedule' : 'Set Start Date'}
                  </button>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Onboarding & setup */}
      <div className="card p-4">
        <p className="text-[11px] font-semibold uppercase tracking-wide text-gray-400 mb-2.5 flex items-center gap-1.5"><Receipt size={13} /> Onboarding &amp; Setup</p>
        {onboardingRows.length === 0 ? (
          <p className="text-[11px] text-gray-400">Nothing on file yet — set a start date above to load the onboarding fee.</p>
        ) : (
          <DataTable
            rows={onboardingRows}
            keyFn={(t) => t.id}
            columns={[
              { header: 'Date', render: (t) => t.transaction_date },
              { header: 'Vehicle', render: (t) => t.linked_vehicle?.plate_number ?? '—' },
              { header: 'Description', render: (t) => t.description ?? '—' },
              { header: 'Amount', render: (t) => <span className={`font-medium ${t.direction === 'in' ? 'text-positive' : ''}`}>{t.direction === 'in' ? '+' : '−'}{fmt(t.amount)}</span> },
              statusColumn,
              actionColumn((t) => (t.type === 'onboarding_fee' ? 'Confirm' : 'Approve'), actOn),
            ]}
          />
        )}
      </div>

      {/* Monthly management fees */}
      <div className="card p-4">
        <p className="text-[11px] font-semibold uppercase tracking-wide text-gray-400 mb-2.5 flex items-center gap-1.5"><TrendingUp size={13} /> Monthly Management Fees</p>
        {monthlyFeeRows.length === 0 ? (
          <p className="text-[11px] text-gray-400">Nothing on file yet.</p>
        ) : (
          <DataTable
            rows={monthlyFeeRows}
            keyFn={(t) => t.id}
            columns={[
              { header: 'Date', render: (t) => t.transaction_date },
              { header: 'Vehicle', render: (t) => t.linked_vehicle?.plate_number ?? '—' },
              { header: 'Amount', render: (t) => <span className="font-medium text-positive">+{fmt(t.amount)}</span> },
              statusColumn,
              actionColumn(() => 'Approve', actOn),
            ]}
          />
        )}
      </div>

      {/* Weekly payments */}
      <div className="card p-4">
        <p className="text-[11px] font-semibold uppercase tracking-wide text-gray-400 mb-2.5 flex items-center gap-1.5"><Wallet size={13} /> Weekly Payments</p>
        {weeklyPaymentRows.length === 0 ? (
          <p className="text-[11px] text-gray-400">Nothing on file yet.</p>
        ) : (
          <DataTable
            rows={weeklyPaymentRows}
            keyFn={(t) => t.id}
            columns={[
              { header: 'Date', render: (t) => t.transaction_date },
              { header: 'Vehicle', render: (t) => t.linked_vehicle?.plate_number ?? '—' },
              { header: 'Amount', render: (t) => <span className="font-medium">−{fmt(t.amount)}</span> },
              statusColumn,
              actionColumn(() => 'Confirm Paid', (t) => confirmPaid(t.id)),
            ]}
          />
        )}
      </div>

      {schedulingVehicle && (
        <SetVehicleStartDateDrawer
          vehicle={schedulingVehicle}
          onClose={() => setSchedulingVehicle(null)}
          onSaved={reload}
        />
      )}
    </div>
  );
}
