/*
# Car-management financial model: owners, onboarding, weekly obligations

Kivu Ride runs two business lines: car management (managing third-party-
owned cars, staffed with Kivu's own drivers in two shifts) and platform
trip commissions. This migration builds the car-management money model,
confirmed directly with the operator:

- Each managed car has an OWNER (name, phone, bank details) who is paid
  a flat 240,000 RWF/week (40,000/day x 6 operational days), regardless
  of how much was actually collected from the two shift drivers that
  week - Kivu absorbs collection risk, the owner doesn't. Paid from I&M.
- The two shift drivers together pay 60,000/day x 6 = 360,000/week per
  car (this is exactly the existing driver_deposits system - 30,000/day
  x 6 = 180,000/week per driver, already built). That money lands in
  Bank of Kigali. It is NOT a refundable security deposit; it's the
  car's operating remittance. The gap between what's collected (360k)
  and what's paid to the owner (240k) is Kivu's management margin -
  120,000/week per car - which belongs in Equity, recognized
  automatically rather than manually entered.
- Owners also pay Kivu a flat monthly management fee (30,000/month),
  separate from the weekly margin above, also destined for Equity.
- Onboarding a new managed car: a one-time 140,000 fee (120k device +
  20k branding), landing in Bank of Kigali. Costs: device 90k, branding
  15k, uniforms for the two assigned drivers 15k (7,500 each) - all
  booked as supplier payments, leaving a one-time onboarding margin.

Both the weekly margin and monthly management fee are schedule-driven
(from the vehicle's operation_start_date), not tied to any single
driver deposit event, so they're generated by sync_vehicle_obligations()
rather than a per-row trigger - callable any time, idempotent (only
inserts periods that haven't been recognized yet), and safe to call
repeatedly as the app does on every Finance page load. Owner payouts are
inserted as 'pending' (a real bank transfer Finance must still execute)
while margin and management fee post as 'posted' immediately (they're
just recognition of money already sitting in the accounts).

No existing vehicle has an owner_id yet - the operator will provide the
8 real owners' details next, at which point sync_vehicle_obligations()
activates itself for each car the moment it's linked. Nothing here
generates a single transaction until that link exists.
*/

-- ============================================================
-- VEHICLE OWNERS
-- ============================================================
CREATE TABLE IF NOT EXISTS vehicle_owners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  phone text NOT NULL,
  email text,
  bank_name text,
  account_number text,
  notes text,
  created_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE vehicle_owners ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vehicle_owners_select" ON vehicle_owners;
CREATE POLICY "vehicle_owners_select" ON vehicle_owners FOR SELECT TO authenticated
  USING (current_department_slug() = 'finance' OR is_managing_director());

DROP POLICY IF EXISTS "vehicle_owners_insert" ON vehicle_owners;
CREATE POLICY "vehicle_owners_insert" ON vehicle_owners FOR INSERT TO authenticated
  WITH CHECK (current_department_slug() = 'finance' OR is_managing_director());

DROP POLICY IF EXISTS "vehicle_owners_update" ON vehicle_owners;
CREATE POLICY "vehicle_owners_update" ON vehicle_owners FOR UPDATE TO authenticated
  USING (current_department_slug() = 'finance' OR is_managing_director())
  WITH CHECK (current_department_slug() = 'finance' OR is_managing_director());

DROP POLICY IF EXISTS "vehicle_owners_delete" ON vehicle_owners;
CREATE POLICY "vehicle_owners_delete" ON vehicle_owners FOR DELETE TO authenticated
  USING (current_department_slug() = 'finance' OR is_managing_director());

-- ============================================================
-- VEHICLES: link to owner + per-car overrides (contract can vary)
-- ============================================================
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES vehicle_owners(id) ON DELETE SET NULL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS weekly_owner_payout_amount numeric;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS monthly_management_fee_amount numeric;

-- ============================================================
-- FINANCE_TRANSACTIONS: two new types
-- ============================================================
ALTER TABLE finance_transactions DROP CONSTRAINT IF EXISTS finance_transactions_type_check;
ALTER TABLE finance_transactions ADD CONSTRAINT finance_transactions_type_check
  CHECK (type IN ('revenue', 'fleet_collection', 'vehicle_owner_payment', 'payroll', 'supplier_payment', 'transfer', 'expense_claim', 'other', 'onboarding_fee', 'management_margin'));

CREATE OR REPLACE FUNCTION finance_type_prefix(p_type text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE p_type
    WHEN 'revenue' THEN 'REV'
    WHEN 'fleet_collection' THEN 'DRV'
    WHEN 'vehicle_owner_payment' THEN 'OWN'
    WHEN 'payroll' THEN 'PAY'
    WHEN 'supplier_payment' THEN 'SUP'
    WHEN 'transfer' THEN 'TRF'
    WHEN 'expense_claim' THEN 'EXP'
    WHEN 'onboarding_fee' THEN 'ONB'
    WHEN 'management_margin' THEN 'MGN'
    ELSE 'OTH'
  END;
$$;

-- ============================================================
-- AUTO-RECOGNITION: weekly margin, weekly owner payout, monthly fee
-- ============================================================
CREATE OR REPLACE FUNCTION sync_vehicle_obligations()
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_vehicle record;
  v_equity_id uuid;
  v_im_id uuid;
  v_owner_name text;
  v_weeks_elapsed int;
  v_months_elapsed int;
  v_existing_count int;
  v_margin_amount numeric;
  v_payout_amount numeric;
  v_fee_amount numeric;
  i int;
BEGIN
  IF current_department_slug() <> 'finance' AND NOT is_managing_director() THEN
    RAISE EXCEPTION 'Only Finance or the MD can sync vehicle obligations';
  END IF;

  SELECT id INTO v_equity_id FROM finance_accounts WHERE key = 'equity';
  SELECT id INTO v_im_id FROM finance_accounts WHERE key = 'im_bank';
  IF v_equity_id IS NULL OR v_im_id IS NULL THEN RETURN; END IF;

  FOR v_vehicle IN SELECT * FROM vehicles WHERE owner_id IS NOT NULL AND operation_start_date IS NOT NULL LOOP
    SELECT full_name INTO v_owner_name FROM vehicle_owners WHERE id = v_vehicle.owner_id;
    v_payout_amount := COALESCE(v_vehicle.weekly_owner_payout_amount, 240000);
    v_margin_amount := 360000 - v_payout_amount;
    v_fee_amount := COALESCE(v_vehicle.monthly_management_fee_amount, 30000);
    v_weeks_elapsed := GREATEST(floor((CURRENT_DATE - v_vehicle.operation_start_date) / 7)::int, 0);

    -- Weekly management margin (recognized immediately - it's already sitting in BK)
    SELECT count(*) INTO v_existing_count FROM finance_transactions
      WHERE type = 'management_margin' AND linked_vehicle_id = v_vehicle.id AND system_generated = true;
    IF v_weeks_elapsed > v_existing_count AND v_margin_amount > 0 THEN
      FOR i IN v_existing_count..(v_weeks_elapsed - 1) LOOP
        INSERT INTO finance_transactions (type, account_id, direction, amount, transaction_date, description, counterparty, linked_vehicle_id, status, system_generated, created_at)
        VALUES ('management_margin', v_equity_id, 'in', v_margin_amount, v_vehicle.operation_start_date + (i * 7),
                'Weekly management margin — ' || v_vehicle.plate_number, v_owner_name, v_vehicle.id, 'posted', true, now());
      END LOOP;
    END IF;

    -- Weekly owner payout (a real transfer - stays pending until Finance actually pays it)
    SELECT count(*) INTO v_existing_count FROM finance_transactions
      WHERE type = 'vehicle_owner_payment' AND linked_vehicle_id = v_vehicle.id AND system_generated = true;
    IF v_weeks_elapsed > v_existing_count THEN
      FOR i IN v_existing_count..(v_weeks_elapsed - 1) LOOP
        INSERT INTO finance_transactions (type, account_id, direction, amount, transaction_date, description, counterparty, linked_vehicle_id, status, system_generated, created_at)
        VALUES ('vehicle_owner_payment', v_im_id, 'out', v_payout_amount, v_vehicle.operation_start_date + (i * 7),
                'Weekly owner payout — ' || v_vehicle.plate_number, v_owner_name, v_vehicle.id, 'pending', true, now());
      END LOOP;
    END IF;

    -- Monthly management fee (recognized immediately, separate from the weekly margin above)
    v_months_elapsed := GREATEST((EXTRACT(YEAR FROM age(CURRENT_DATE, v_vehicle.operation_start_date)) * 12
      + EXTRACT(MONTH FROM age(CURRENT_DATE, v_vehicle.operation_start_date)))::int, 0);
    SELECT count(*) INTO v_existing_count FROM finance_transactions
      WHERE type = 'revenue' AND linked_vehicle_id = v_vehicle.id AND system_generated = true
        AND description LIKE 'Monthly management fee%';
    IF v_months_elapsed > v_existing_count AND v_fee_amount > 0 THEN
      FOR i IN v_existing_count..(v_months_elapsed - 1) LOOP
        INSERT INTO finance_transactions (type, account_id, direction, amount, transaction_date, description, counterparty, linked_vehicle_id, status, system_generated, created_at)
        VALUES ('revenue', v_equity_id, 'in', v_fee_amount, (v_vehicle.operation_start_date + (i || ' months')::interval)::date,
                'Monthly management fee — ' || v_vehicle.plate_number, v_owner_name, v_vehicle.id, 'posted', true, now());
      END LOOP;
    END IF;
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION sync_vehicle_obligations() TO authenticated;

-- Marks a pending weekly owner payout as actually paid, the same shape
-- as confirm_driver_deposit - a dedicated RPC rather than widening the
-- general UPDATE policy, and it's the only way a system_generated row's
-- status can move (the drawer's own Edit is locked for those).
CREATE OR REPLACE FUNCTION mark_vehicle_owner_payment_paid(p_transaction_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF current_department_slug() <> 'finance' AND NOT is_managing_director() THEN
    RAISE EXCEPTION 'Only Finance or the MD can mark an owner payment as paid';
  END IF;

  UPDATE finance_transactions
  SET status = 'posted', checked_by = auth.uid(), checked_at = now(), updated_at = now()
  WHERE id = p_transaction_id AND type = 'vehicle_owner_payment' AND status = 'pending';
END;
$$;

GRANT EXECUTE ON FUNCTION mark_vehicle_owner_payment_paid(uuid) TO authenticated;
