/*
# Script Book v1.0 - seed

Every situation from the Kivu Ride Call Center Script Book (v1.0,
October 2026), as cards: what to say (the book's exact wording), what
to do, what to collect, and which department owns it. The MD edits
these in the app from now on; this seed only runs when the table is
empty, so it never overwrites edits.
*/

DO $seed$
BEGIN
IF EXISTS (SELECT 1 FROM script_cards) THEN RETURN; END IF;

INSERT INTO script_cards (section_key, section_title, section_order, card_order, situation, say, steps, collect, owner_duty, default_priority, is_quick) VALUES

-- ============ Quick reference (pinned) ============
('quick', 'Quick reference', 0, 1, 'Standard opening',
 $$Thank you for contacting Kivu Ride on 6023. My name is [name]. How may I assist you today?$$,
 ARRAY[$$Listen first — let the caller explain. Don't interrupt unless someone's safety is involved.$$,
       $$Confirm the important facts back: name, phone number, pickup, destination, vehicle or trip details.$$],
 '{}', NULL, 'normal', true),
('quick', 'Quick reference', 0, 2, 'Standard case closing',
 $$Thank you for choosing Kivu Ride. Your reference is [reference]. We will update you within two hours. You may contact us again free of charge on 6023.$$,
 ARRAY[$$Confirm the caller understands the next step.$$, $$Give the reference whenever a case was created.$$],
 '{}', NULL, 'normal', true),
('quick', 'Quick reference', 0, 3, 'Fare guide',
 $$Based on the route entered in our system, the estimated fare is approximately RWF [amount]. The final fare may change if the route, distance, stops or waiting time changes.$$,
 ARRAY[$$Base fare: RWF 1,600 — includes the first kilometre.$$,
       $$Distance: RWF 1,000 for each kilometre after the first.$$,
       $$Waiting: the first 15 minutes are free, then RWF 1,500 per 30 minutes.$$,
       $$Cancellation: there is currently no cancellation fee (still record repeated or suspicious cancellations).$$],
 '{}', NULL, 'normal', true),
('quick', 'Quick reference', 0, 4, 'Payment methods',
 NULL,
 ARRAY[$$Cash, MTN MoMo, Airtel Money, card, or an authorised Smart Account balance.$$,
       $$Never ask for a Mobile Money PIN, card number, CVV, card PIN, OTP or password.$$],
 '{}', NULL, 'normal', true),
('quick', 'Quick reference', 0, 5, 'Emergency numbers',
 $$Your safety comes first. Please call [112/113/912/111] now. I am recording your exact location and immediately notifying Kivu Ride management.$$,
 ARRAY[$$112 — general emergency / police.$$, $$113 — traffic accident.$$, $$912 — ambulance / medical emergency.$$, $$111 — fire and rescue.$$],
 '{}', 'route_md', 'emergency', true),
('quick', 'Quick reference', 0, 6, 'Escalation confirmation',
 $$I have recorded the issue and assigned it to [department]. Your reference is [reference]. You will receive an initial response within two hours.$$,
 ARRAY[$$When unsure who owns it, create the case first and assign it to the Managing Director.$$],
 '{}', NULL, 'normal', true),
('quick', 'Quick reference', 0, 7, 'When you do not know',
 $$Let me confirm the correct information for you.$$,
 ARRAY[$$Create or escalate the case rather than guessing. Accuracy protects the passenger, driver, agent and Kivu Ride.$$],
 '{}', NULL, 'normal', true),
('quick', 'Quick reference', 0, 8, 'Non-negotiable rules',
 NULL,
 ARRAY[$$Never guarantee a pickup time the system and driver have not confirmed.$$,
       $$Never promise a refund, discount, free ride or compensation without authorisation.$$,
       $$Never request a Mobile Money PIN, bank-card PIN, CVV, OTP, app password or financial credential.$$,
       $$Never disclose another passenger's, driver's, employee's or partner's private information.$$,
       $$Never share confidential company, contract or personnel information.$$,
       $$Never argue with, insult, blame or belittle a caller.$$,
       $$Never falsify a trip, complaint, payment, dispatch or follow-up record.$$,
       $$Never close a serious safety complaint without proper escalation.$$,
       $$Never mark a case resolved before the action is complete and the customer is informed.$$,
       $$Never say calls are recorded — calls are not currently recorded.$$],
 '{}', NULL, 'normal', true),

-- ============ Booking & dispatch ============
('booking', 'Booking & dispatch', 1, 1, 'Immediate ride',
 $$May I have your name, the phone number the driver can reach, your exact pickup location with a nearby landmark, and your destination?$$,
 ARRAY[$$Read back the name, phone number, pickup point, landmark, destination and payment method. Correct any difference before selecting a driver.$$,
       $$Create the booking in the operations platform, find nearby cars and dispatch.$$,
       $$Wait for the driver to accept in the driver app.$$,
       $$Tell the passenger a driver was found (they also get an SMS).$$,
       $$Call the driver to confirm the request is visible and they are heading to the pickup.$$,
       $$Record the dispatch as confirmed only after the driver confirms movement toward the pickup.$$],
 ARRAY[$$Passenger name$$, $$Reachable phone number$$, $$Exact pickup location and landmark$$, $$Destination (needed for the fare estimate)$$, $$Payment method$$,
       $$When relevant: ride category, number of passengers, stops or return trip, accessibility or luggage needs, Smart Account authorisation$$],
 NULL, 'normal', false),
('booking', 'Booking & dispatch', 1, 2, 'Driver accepted — tell the passenger',
 $$Your driver has accepted the request and is coming from [approximate area]. You will receive an SMS, and the driver will call you shortly. Please keep your phone available.$$,
 ARRAY[$$Then call the driver and confirm they are heading to the pickup.$$], '{}', NULL, 'normal', false),
('booking', 'Booking & dispatch', 1, 3, 'Scheduled ride',
 $$I have scheduled your ride for [date] at [time], from [pickup] to [destination]. [Stops/return details]. Your payment method is [method]. Is everything correct?$$,
 ARRAY[$$Collect the date and exact pickup time.$$, $$Repeat the date, time, pickup and destination before saving.$$,
       $$Never guarantee a pickup time until the system and the assigned driver have confirmed it.$$],
 ARRAY[$$Date and exact pickup time$$, $$Pickup and destination$$, $$Payment method$$], NULL, 'normal', false),
('booking', 'Booking & dispatch', 1, 4, 'Airport, intercity, multi-stop or round trip',
 NULL,
 ARRAY[$$Airport: confirm the terminal or flight-related pickup point, pickup time, luggage needs and a reachable phone number.$$,
       $$Intercity: confirm origin, destination district/city, departure time, number of passengers and whether a return is needed.$$,
       $$Multi-stop: record every stop in order; explain that distance and waiting may affect the final fare.$$,
       $$Round trip: confirm whether the driver waits or returns later; explain the free 15 minutes of waiting and the charge after.$$],
 '{}', NULL, 'normal', false),
('booking', 'Booking & dispatch', 1, 5, 'Nearest driver is far away',
 $$The nearest available driver is currently approximately [time] away. Would you like me to dispatch that driver for you?$$,
 ARRAY[$$Never say "there are no drivers" before checking the next available vehicle.$$,
       $$Explain the nearest driver is farther away or finishing another trip.$$,
       $$Give the system's estimate — don't shorten it to keep the booking. Let the passenger decide.$$,
       $$If they accept: dispatch, get acceptance, confirm by phone, update the passenger.$$,
       $$If they decline: close politely and record that the passenger declined the wait.$$],
 '{}', NULL, 'normal', false),

-- ============ Fares & payments ============
('fares_payments', 'Fares & payments', 2, 1, 'Fare estimate',
 $$Based on the route entered in our system, the estimated fare is approximately RWF [amount]. The final fare may change if the route, distance, stops or waiting time changes.$$,
 ARRAY[$$Give the system estimate only. The completed trip and recorded waiting decide the final fare.$$], '{}', NULL, 'normal', false),
('fares_payments', 'Fares & payments', 2, 2, 'Helping with a payment method',
 NULL,
 ARRAY[$$Cash: passenger pays by cash according to the active payment flow; check the trip status in the system.$$,
       $$MTN MoMo / Airtel Money: guide them through the approved flow. Never ask for the PIN or OTP.$$,
       $$Card: use the approved card flow. Never ask for the full card number, CVV, PIN or OTP.$$,
       $$Smart Account: verify the member with the dedicated booking passcode, then charge the account.$$],
 '{}', NULL, 'normal', false),
('fares_payments', 'Fares & payments', 2, 3, 'Payment failed',
 $$I have recorded the trip and payment details. This requires technical review, so I am assigning it now. You will receive an initial response within two hours.$$,
 ARRAY[$$Check the trip and payment status.$$, $$Collect the error message and transaction reference if available.$$,
       $$Create a case for IT (or Finance if it's a money question).$$],
 ARRAY[$$Trip reference / date and time$$, $$Payment method$$, $$Error message$$, $$Transaction reference$$], 'route_it', 'normal', false),
('fares_payments', 'Fares & payments', 2, 4, 'Charged twice / missing amount',
 $$I am sorry that you experienced this. I will record the details accurately and send the case to the responsible team. You will receive an initial response within two hours.$$,
 ARRAY[$$Do not promise a refund.$$, $$Record the amount, time, method and reference.$$,
       $$Assign to Finance for approval; ask IT to verify the transaction when its status is unclear.$$],
 ARRAY[$$Amount$$, $$Date and time$$, $$Payment method$$, $$Transaction reference$$], 'route_finance', 'normal', false),

-- ============ Before pickup ============
('before_pickup', 'Before pickup', 3, 1, 'Driver is late',
 $$I am checking the driver's current status now. Please allow me a moment while I confirm the location directly.$$,
 ARRAY[$$Check the live status.$$, $$Call the driver and get an updated location.$$, $$Give the passenger the best available estimate.$$],
 '{}', 'route_operations', 'normal', false),
('before_pickup', 'Before pickup', 3, 2, 'Passenger can''t find the driver',
 NULL,
 ARRAY[$$Confirm the pickup landmark, vehicle registration and phone contact.$$, $$Connect the passenger and driver when necessary.$$],
 '{}', 'route_operations', 'normal', false),
('before_pickup', 'Before pickup', 3, 3, 'Driver can''t find the passenger',
 NULL,
 ARRAY[$$Call the passenger and confirm the landmark.$$, $$Pass the corrected directions to the driver.$$],
 '{}', 'route_operations', 'normal', false),
('before_pickup', 'Before pickup', 3, 4, 'Driver cancelled',
 NULL,
 ARRAY[$$Check the trip status.$$, $$Find another nearby driver.$$, $$Update the passenger.$$],
 '{}', 'route_operations', 'normal', false),
('before_pickup', 'Before pickup', 3, 5, 'Passenger cancels',
 NULL,
 ARRAY[$$Confirm the cancellation. There is currently no cancellation fee.$$, $$Record the outcome (note repeated or suspicious cancellations).$$],
 '{}', NULL, 'normal', false),
('before_pickup', 'Before pickup', 3, 6, 'Passenger changes destination',
 NULL,
 ARRAY[$$Update or recreate the route in the approved system flow.$$, $$Explain the fare estimate may change.$$],
 '{}', NULL, 'normal', false),

-- ============ During the trip ============
('during_trip', 'During the trip', 4, 1, 'Route concern',
 NULL,
 ARRAY[$$Confirm the active trip and destination.$$, $$Check the system route.$$, $$Escalate technical route or fare issues to IT.$$],
 ARRAY[$$Trip reference$$, $$Pickup and destination$$, $$What the caller says is wrong with the route$$], 'route_it', 'normal', false),
('during_trip', 'During the trip', 4, 2, 'Fare disagreement',
 NULL,
 ARRAY[$$Don't decide who is right during the call.$$, $$Record the displayed fare, the amount requested and the payment method.$$,
       $$Assign it: technical fare calculation to IT, money/refund questions to Finance.$$],
 ARRAY[$$Displayed fare$$, $$Amount requested$$, $$Payment method$$, $$Trip reference$$], 'route_it', 'normal', false),
('during_trip', 'During the trip', 4, 3, 'Driver conduct',
 $$I am sorry that you experienced this. I will record the details accurately and send the case to the responsible team. You will receive an initial response within two hours.$$,
 ARRAY[$$Listen without blaming either party.$$, $$Record the exact behaviour described.$$, $$Link the driver or car and assign to Operations.$$],
 ARRAY[$$Driver name or vehicle plate$$, $$Trip date and time$$, $$Exactly what happened$$], 'route_operations', 'normal', false),
('during_trip', 'During the trip', 4, 4, 'Vehicle cleanliness or condition',
 NULL,
 ARRAY[$$Record the vehicle registration, trip and complaint details.$$, $$Assign to the Fleet Manager.$$],
 ARRAY[$$Vehicle plate$$, $$Trip date$$, $$What was wrong$$], 'fleet_manager', 'normal', false),
('during_trip', 'During the trip', 4, 5, 'Breakdown during a trip',
 NULL,
 ARRAY[$$Confirm the passenger is safe and get the exact location.$$, $$Notify the Fleet Manager and coordinate support (another car if needed).$$],
 ARRAY[$$Exact location$$, $$Vehicle plate$$, $$Is the passenger still in the car?$$], 'fleet_manager', 'urgent', false),
('during_trip', 'During the trip', 4, 6, 'Danger or harassment',
 $$Your safety comes first. Please call [112/113/912/111] now. I am recording your exact location and immediately notifying Kivu Ride management.$$,
 ARRAY[$$Treat it as an emergency — stop routine troubleshooting.$$, $$Help the caller contact public emergency services.$$,
       $$Notify the Managing Director immediately.$$],
 ARRAY[$$Exact location$$, $$Vehicle plate$$, $$People involved$$], 'route_md', 'emergency', false),

-- ============ Lost property ============
('lost_property', 'Lost property', 5, 1, 'Passenger lost an item',
 $$I will contact the driver and ask them to check the vehicle. I cannot guarantee recovery, but I will record the report and help connect you if the item is found.$$,
 ARRAY[$$Identify the trip.$$, $$Get a detailed description of the item.$$, $$Contact the driver and ask them to check the car.$$,
       $$If found, connect the passenger and driver — share contact details only for the return.$$, $$Record the agreed handover and the outcome.$$,
       $$Never guarantee the item will be found.$$],
 ARRAY[$$Passenger name and reachable phone$$, $$Trip date, approximate time, pickup and destination$$,
       $$Item description: colour, brand, identifying features$$, $$Driver or vehicle details if known$$], 'fleet_manager', 'normal', false),

-- ============ Complaints ============
('complaint', 'Complaints', 6, 1, 'Taking a complaint',
 $$I am sorry that you experienced this. I will record the details accurately and send the case to the responsible team. You will receive an initial response within two hours.$$,
 ARRAY[$$Listen, acknowledge, clarify the facts.$$, $$Create the case and assign the owner.$$, $$Give the reference.$$,
       $$Only authorised departments approve refunds, fare corrections, discounts, compensation, free rides or suspensions — never promise them.$$],
 ARRAY[$$What the caller says happened, without assumptions$$, $$Trip, driver or vehicle details$$], 'route_md', 'normal', false),
('complaint', 'Complaints', 6, 2, 'Complaint: technical trip or fare',
 NULL, ARRAY[$$Assign to IT.$$], ARRAY[$$Trip reference$$, $$Displayed fare or error$$], 'route_it', 'normal', false),
('complaint', 'Complaints', 6, 3, 'Complaint: payment or refund',
 NULL, ARRAY[$$Assign to Finance, with IT verification when the transaction status is unclear.$$, $$Do not promise a refund.$$],
 ARRAY[$$Amount$$, $$Payment method$$, $$Transaction reference$$], 'route_finance', 'normal', false),
('complaint', 'Complaints', 6, 4, 'Complaint: driver behaviour',
 NULL, ARRAY[$$Link the driver or car.$$, $$Assign to Operations.$$], ARRAY[$$Driver name or plate$$, $$What happened$$], 'route_operations', 'normal', false),
('complaint', 'Complaints', 6, 5, 'Complaint: vehicle condition',
 NULL, ARRAY[$$Assign to the Fleet Manager.$$], ARRAY[$$Vehicle plate$$, $$What was wrong$$], 'fleet_manager', 'normal', false),
('complaint', 'Complaints', 6, 6, 'Complaint: unclear who owns it',
 NULL, ARRAY[$$Escalate to the Managing Director for assignment.$$], '{}', 'route_md', 'normal', false),
('complaint', 'Complaints', 6, 7, 'Upset or abusive caller',
 $$I want to help you. I can continue assisting, but I need us to keep the conversation respectful. If the abusive language continues, I will have to end the call and record the case.$$,
 ARRAY[$$Upset but cooperative: slow down, acknowledge, focus on the next action.$$,
       $$Repeated interruption: politely ask for one minute to confirm the facts and explain the next step.$$,
       $$Insults: give one calm warning (above).$$,
       $$Threats or immediate danger: record the exact words and escalate as a safety case.$$,
       $$End the call only after the warning, unless there's an immediate threat — and record why it ended.$$],
 '{}', NULL, 'normal', false),

-- ============ Emergency & safety ============
('emergency', 'Emergency & safety', 7, 1, 'Emergency — first actions',
 $$Your safety comes first. Please call [112/113/912/111] now. I am recording your exact location and immediately notifying Kivu Ride management.$$,
 ARRAY[$$Ask: "Are you or anyone else in immediate danger or injured?"$$,
       $$Ask: "What is your exact location? Please give the nearest landmark and vehicle registration if available."$$,
       $$Call the right service (or tell the caller to) — public help comes first.$$,
       $$The MD and Fleet Manager are alerted automatically when you save.$$,
       $$Keep the record open. The two-hour standard doesn't apply — act immediately.$$],
 ARRAY[$$Time, caller and phone$$, $$Exact location$$, $$Vehicle and trip$$, $$People involved$$, $$Injuries or danger reported$$, $$Emergency number contacted$$],
 'route_md', 'emergency', false),
('emergency', 'Emergency & safety', 7, 2, 'Traffic accident',
 NULL, ARRAY[$$Call 113. If anyone is injured, also call 912.$$, $$The MD and Fleet Manager are alerted when you save.$$],
 ARRAY[$$Exact location$$, $$Vehicle plate$$, $$Injuries$$], 'route_md', 'emergency', false),
('emergency', 'Emergency & safety', 7, 3, 'Medical emergency',
 NULL, ARRAY[$$Call 912.$$, $$Keep the caller focused on location and immediate safety.$$], ARRAY[$$Exact location$$, $$Who needs help$$], 'route_md', 'emergency', false),
('emergency', 'Emergency & safety', 7, 4, 'Fire',
 NULL, ARRAY[$$Call 111.$$, $$Tell the caller to move away from the vehicle or danger if it is safe to do so.$$], ARRAY[$$Exact location$$, $$Vehicle plate$$], 'route_md', 'emergency', false),
('emergency', 'Emergency & safety', 7, 5, 'Threat or harassment',
 NULL, ARRAY[$$Call 112 when immediate police help is needed.$$, $$Do not confront the alleged offender through the caller.$$, $$Record the exact words used.$$],
 ARRAY[$$Exact location$$, $$People involved$$, $$Exact words or actions$$], 'route_md', 'emergency', false),

-- ============ Driver support ============
('driver_support', 'Driver support', 8, 1, 'Verify the driver first',
 $$Please confirm your registered full name, registered phone number and vehicle plate number so I can locate the correct driver account.$$,
 ARRAY[$$Ask only for the registered name, registered phone and plate number.$$,
       $$Never ask for a Mobile Money PIN or OTP, card PIN, CVV or password, or another driver's details.$$,
       $$If verification fails: don't disclose account, trip, earnings or passenger information — create a verification-support case.$$],
 ARRAY[$$Registered full name$$, $$Registered phone number$$, $$Vehicle plate$$], 'route_it', 'normal', false),
('driver_support', 'Driver support', 8, 2, 'Login problem',
 $$I have recorded the trip and account details. This requires technical review, so I am assigning it to IT now. You will receive an initial response within two hours.$$,
 ARRAY[$$Guide the driver through the normal login process.$$, $$If it still fails, record the error and assign to IT.$$],
 ARRAY[$$Error message$$, $$Phone model if relevant$$], 'route_it', 'normal', false),
('driver_support', 'Driver support', 8, 3, 'Trip not visible / can''t accept, start or end',
 NULL,
 ARRAY[$$Confirm connectivity, active status and the app screen.$$, $$Record the trip reference, screen state and error message.$$, $$If standard guidance fails, assign to IT.$$],
 ARRAY[$$Trip reference$$, $$What the screen shows$$, $$Error message$$], 'route_it', 'normal', false),
('driver_support', 'Driver support', 8, 4, 'Missing earnings',
 NULL,
 ARRAY[$$Collect the details below and assign directly to IT.$$],
 ARRAY[$$Trip reference$$, $$Date$$, $$Displayed amount$$, $$Screenshot or reference if available$$], 'route_it', 'normal', false),
('driver_support', 'Driver support', 8, 5, 'Payment status question',
 NULL,
 ARRAY[$$Confirm only what is visible and authorised.$$, $$Route transaction inconsistencies to IT / Finance.$$],
 '{}', 'route_it', 'normal', false),
('driver_support', 'Driver support', 8, 6, 'Driver suspended',
 NULL,
 ARRAY[$$Identify the stated reason.$$, $$If it's unpaid cash-trip commission, tell the driver to complete the required payment.$$, $$Otherwise assign to IT / Management.$$],
 ARRAY[$$Stated reason$$], 'route_it', 'normal', false),
('driver_support', 'Driver support', 8, 7, 'Driver had an accident',
 $$Your safety comes first. Please call [112/113/912/111] now. I am recording your exact location and immediately notifying Kivu Ride management.$$,
 ARRAY[$$Confirm immediate safety; use the emergency procedure where needed.$$, $$The MD and Fleet Manager are alerted when you save.$$],
 ARRAY[$$Exact location$$, $$Vehicle plate$$, $$Injuries$$, $$Passenger involved?$$], 'route_md', 'emergency', false),
('driver_support', 'Driver support', 8, 8, 'Driver breakdown',
 NULL,
 ARRAY[$$Confirm the location, plate, passenger status and whether a trip is active.$$, $$Assign to the Fleet Manager.$$],
 ARRAY[$$Exact location$$, $$Vehicle plate$$, $$Trip active? Passenger on board?$$], 'fleet_manager', 'urgent', false),
('driver_support', 'Driver support', 8, 9, 'Driver–passenger dispute',
 NULL,
 ARRAY[$$Record the driver's report and the trip details without taking sides.$$, $$Conduct matters go to Operations; technical or fare matters to IT.$$,
       $$The call center records facts and coordinates — it never decides liability, discipline or compensation.$$],
 ARRAY[$$Trip reference$$, $$Driver's account of what happened$$], 'route_operations', 'normal', false),
('driver_support', 'Driver support', 8, 10, 'Passenger can''t be reached',
 NULL, ARRAY[$$Ask the driver to call the passenger and confirm the pickup.$$, $$Record the unsuccessful contact attempts.$$], '{}', NULL, 'normal', false),
('driver_support', 'Driver support', 8, 11, 'Driver found an item',
 NULL, ARRAY[$$Record the trip and item description.$$, $$Contact the passenger and arrange a safe, documented return.$$],
 ARRAY[$$Trip date and time$$, $$Item description$$], 'fleet_manager', 'normal', false),

-- ============ Fleet owners & partners ============
('fleet_partner', 'Fleet owners & partners', 9, 1, 'Owner asks about payment status',
 $$I have recorded your question regarding vehicle [plate]. Management will review the details and contact you with an initial response within two hours.$$,
 ARRAY[$$Verify the owner, identify the vehicle.$$, $$Share only the status visible for that verified owner and vehicle.$$, $$Don't interpret or change management's calculations.$$],
 ARRAY[$$Owner name$$, $$Vehicle plate$$], 'route_finance', 'normal', false),
('fleet_partner', 'Fleet owners & partners', 9, 2, 'Owner earnings question',
 NULL, ARRAY[$$Record the vehicle, period and the specific discrepancy.$$, $$Assign to Management / Finance.$$],
 ARRAY[$$Vehicle plate$$, $$Period$$, $$The discrepancy$$], 'route_finance', 'normal', false),
('fleet_partner', 'Fleet owners & partners', 9, 3, 'Vehicle performance question',
 NULL, ARRAY[$$Collect the question and assign to Management for a formal response.$$], ARRAY[$$Vehicle plate$$, $$The question$$], 'route_md', 'normal', false),
('fleet_partner', 'Fleet owners & partners', 9, 4, 'Owner reports maintenance or breakdown',
 NULL, ARRAY[$$Collect the vehicle, location and issue.$$, $$Assign to the Fleet Manager.$$], ARRAY[$$Vehicle plate$$, $$Location$$, $$Issue$$], 'fleet_manager', 'normal', false),
('fleet_partner', 'Fleet owners & partners', 9, 5, 'Contract or confidential terms',
 NULL, ARRAY[$$Do not discuss.$$, $$Record the request and refer it to Management.$$], '{}', 'route_md', 'normal', false),

-- ============ Smart Accounts ============
('smart_account', 'Smart Accounts', 10, 1, 'Booking on a Smart Account',
 $$To confirm that this ride may be charged to the Smart Account, please provide your dedicated booking passcode. Do not provide any Mobile Money, card or banking PIN.$$,
 ARRAY[$$Identify the account and verify the member.$$, $$Ask for the dedicated booking passcode (never a PIN, OTP or password).$$,
       $$Check the balance, create the ride with Smart Account as payment, dispatch and confirm as normal.$$],
 ARRAY[$$Account name$$, $$Member name$$, $$Booking passcode$$], NULL, 'normal', false),
('smart_account', 'Smart Accounts', 10, 2, 'Passcode fails',
 NULL, ARRAY[$$Don't disclose account information or charge the ride.$$, $$Guide the caller to their account manager, or create an IT case.$$], '{}', 'route_it', 'normal', false),
('smart_account', 'Smart Accounts', 10, 3, 'Insufficient balance',
 NULL, ARRAY[$$Explain the visible status. Never override it.$$, $$Guide the account manager through the approved deposit process.$$], '{}', NULL, 'normal', false),
('smart_account', 'Smart Accounts', 10, 4, 'Add/remove member or statement request',
 NULL, ARRAY[$$Guide the account manager through self-service (members) or to the statement/reporting area.$$, $$Agents never add or remove members or change limits themselves.$$,
            $$Escalate technical failures or access problems to IT.$$], '{}', 'route_it', 'normal', false),

-- ============ General enquiries ============
('general', 'General enquiries', 11, 1, 'New rider',
 NULL, ARRAY[$$Explain booking by app or on 6023, the service types (Economy, VIP, Van; airport, intercity, multi-stop, round trip) and payment methods.$$], '{}', NULL, 'normal', false),
('general', 'General enquiries', 11, 2, 'Prospective driver',
 NULL, ARRAY[$$Give only current public onboarding information.$$, $$Assign to Operations.$$], ARRAY[$$Name$$, $$Phone$$, $$Their enquiry$$], 'route_operations', 'normal', false),
('general', 'General enquiries', 11, 3, 'Vehicle / fleet owner lead',
 NULL, ARRAY[$$Explain that Kivu Ride supports fleet onboarding, dispatch, tracking and reporting.$$, $$Assign the lead to Business Development.$$],
 ARRAY[$$Name$$, $$Phone$$, $$Number of vehicles$$], 'route_bizdev', 'normal', false),
('general', 'General enquiries', 11, 4, 'Corporate or family account',
 NULL, ARRAY[$$Explain approved members, prepaid/postpaid options, visibility and call-center booking.$$, $$Assign setup interest to Corporate Accounts.$$],
 ARRAY[$$Organisation$$, $$Contact person$$, $$Phone / email$$], 'route_corporate', 'normal', false),
('general', 'General enquiries', 11, 5, 'Hotel, event or organisation',
 NULL, ARRAY[$$Collect the details below.$$, $$Assign to Business Development.$$],
 ARRAY[$$Organisation$$, $$Contact$$, $$Transport need$$, $$Expected dates$$, $$Volume$$], 'route_bizdev', 'normal', false),
('general', 'General enquiries', 11, 6, 'Government or media',
 NULL, ARRAY[$$Record the request and contact details.$$, $$Refer directly to the Managing Director. Do not make an official statement.$$],
 ARRAY[$$Organisation$$, $$Contact details$$, $$Request$$], 'route_md', 'normal', false),
('general', 'General enquiries', 11, 7, 'Public contact details',
 NULL, ARRAY[$$Call center: 6023 (toll-free, 24/7).$$, $$Email: administration@kivuride.com$$, $$Office: Norrsken House Kigali, 1 KN 78 Street, Kigali.$$], '{}', NULL, 'normal', false);

END $seed$;
